import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import Search from "@/components/Search";
import { CategoriesProvider } from "@/hooks/useCategories";
import { SearchProvider } from "@/hooks/useSearch";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SearchProvider>
          <CategoriesProvider>
            <Search />
            <div className={styles.search__container}>{children}</div>
          </CategoriesProvider>
        </SearchProvider>
      </body>
    </html>
  );
}
